export enum RoomStatusEnum {
    AVAILABLE = 'AVAILABLE',
    OCCUPIED = 'OCCUPIED',
    MAINTENANCE = 'MAINTENANCE',
    BOOKED = 'BOOKED',
    WAITING_FOR_CONFIRMATION = 'WAITING_FOR_CONFIRMATION',
}